### ISSUE TITLE
Want to change css properties

### ISSUE THREAD

**Issue by jaspreet1234567** [nik-christou/lit-element-bootstrap#1]
Hi,

First of all thank you so much for this great documentation. We really need a design system similar to bootstrap.

I have one question - I want to apply my own css on buttons, text-boxes etc. How it could be possible? Please suggest us. How can we override already applied css in our component.

Also what about datepicker, autocomplete etc. things. Are you planning about these?

Regards,
Jaspreet Singh

**Comment by nik-christou** [comment]
Hi Jaspreet,

Apologies for the late response. I am still working on finishing the documentation on how to change the look and feel of the components. At the end it will be a list of CSS custom properties that you can override with your own values. I suggest that you look into the code of the individual web component and see what you can use. If the property you want to use it not there, I will be happy to accept a pull request.

To override a CSS custom property first you need to target the component and then apply the new value:

`bs-button.myClass {
     --bs-button-color: var(#007bff);
}`

Also note that the library is still in alpha version since most likely things will change.

As for the additional components, although it will be very nice to have them, I want to first finish the main parts first.

**Comment by nik-christou** [comment]
Closing as no further action is required
